# Site
# 博客的标题
title: 王欣的博客

seotitle: 王欣的博客|微服务|RPC
# banner显示的子标题
subtitle: 王欣的博客

# banner显示的简短介绍
subtitle_desc: 开源项目提交者

# seo关键字
keywords: 开源项目提交者,dubbo,rpc,apache,架构师

# 博客介绍（同时用于seo）
description: 王欣，Dubbo项目committer、PPMC。专注于rpc、性能相关的技术，拥抱开源。
# 个人介绍
introduction: 锲而不舍、金石可镂

# 博客的favicon图标，支持本地及在线两种方式，本地请将图标放置于 themes/hexo-theme-skapp/source/img 目录下
favicon_ico: /images/wangxin-min.png
# 博客的左上角logo图标，支持本地及在线两种方式
logo: /images/wangxin.png

# 头像/二维码（用于显示在底部）二选一
avatar: https://avatars2.githubusercontent.com/u/827112?s=400&u=b52ee4c5af5eceba6a4d565a0d5e3ed41536c194&v=4

# 文章的默认封面
default_cover: /images/java.png

# header 的背景图
header_cover: /images/banner.jpeg

# 404 页面的背景图
error_page_bg: /images/404.jpg

# 页面加载loading图标
loader_img: http://oo12ugek5.bkt.clouddn.com/blog/images/loader.gif

# 站长信息
author:
  name: Xin Wang(王欣)
  link: https://lovepoem.github.io/
# 用于页面 footer 的站长信息
about:
  info: 王欣的博客，工作生活的一些思考。
  address: Beijing, China
  email: xin.victorwang@gmail.com
language: zh-cn
url: https://lovepoem.github.io/
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
menu:
  home: /
  archive: /archives
  tags: /tags
  github: https://github.com/lovepoem

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/lovepoem/lovepoem.github.io.git
  branch: master
  # Pagination
  ## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-skapp

timezone:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Deployment
## Docs: https://hexo.io/docs/deployment.html
sidebar:
  position: left
scheme: Pisces
toc:
  enable: true
  maxDepth: 3
  # Automatically add list number to toc.
  number: true
  slugify: false
  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
  # Code Highlight theme
  # Available value:
  #    normal | night | night eighties | night blue | night bright
  # https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal
# Baidu statistic
baidu_statistic: baidu_verify_5stQ3RVSV8.html
# Google statistic
google_statistic: google327b939e5efe3f3f.html
# Busuanzi
busuanzi: true
# Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

# Sitemap
sitemap:
  path: sitemap.xml
#  Gitalk
gitTalk:
  enable: true #是否开启
  distractionFreeMode: true # 是否开启分心自由模式 也就是免打扰
  clientId: ab1477fe01cd521ae26e
  clientSecret: 94fa48ef2f297325686aaa6306876b7183b99482
  repo: lovepoem.github.io
  owner: lovepoem
  admin:
    - lovepoem